export default {
  SET_CURRENT: 'SET_CURRENT',
  SET_USER_SEQ: 'SET_USER_SEQ',
  SET_SEQ: 'SET_SEQ',
  RUN_SEQ: 'RUN_SEQ',
  FAILED: 'FAILED',
  SET_IS_RUN: 'SET_IS_RUN',
  ADD_USER_SEQ: 'ADD_USER_SEQ',
  END_GAME: 'END_GAME',
  NEW_GAME: 'NEW_GAME'
}